security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            stateless: true

            guard:
                authenticators:
                    - TravelOrganizer\Security\LegacyAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/auth/log(in|out)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { roles: IS_AUTHENTICATED_FULLY }
