services:
    _defaults:
        autowire: true
        autoconfigure: true

#    TravelOrganizer\Zend\TraceableZendBridge:
#        decorates: TravelOrganizer\Zend\ZendBridge
#        arguments:
#            $cacheDirectory: '%kernel.cache_dir%/xdebug'

    TravelOrganizer\Zend\CoverageZendBridge:
        decorates: TravelOrganizer\Zend\ZendBridge
        arguments:
            $projectDirectory: '%kernel.project_dir%'

    TravelOrganizer\Zend\DataCollector:
        tags:
            - { name: 'data_collector', template: 'zend_collector.html.twig', id: 'zend' }
